# Generated by Django 4.1 on 2022-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(blank=True, max_length=50, verbose_name='pseudonimo'),
        ),
    ]
